### ISSUE TITLE
CVRs6_x64.c:2271:3: error: stray '\36' in program In RxODE

### ISSUE THREAD

**Issue by HongtaoYu** [nlmixrdevelopment/RxODE#117]
Hi, Matt

Currently, I am experiencing a compiling issue. When I updated the version of RxODE from 0.8.0-7 to 0.9.1-7, it failed to compile the code (It definitely worked before with RxODE V0.8.0-7 and the ODEs are the same) and showed these errors "CVRs6_x64.c:2271:3: error: stray '\36' in program".

One test I did was to comment out half of the code, then it did work. However, when compiling the entire code, it didn't.

I have attached the error message for your reference.

Could you kindly explain what is the problem and how to solve this issue? Thank you.

Regards
Hongtao
[Errors.txt](https://github.com/nlmixrdevelopment/RxODE/files/3649218/Errors.txt)

**Comment by mattfidler** [comment]
Hi @HongtaoYu ,

I believe I have fixed this in the github version of RxODE.  I believe there was an interaction between R's garbage collection and `RxODE`'s model generation.  

You can check by using the following command:
```R
devtools::install_github("nlmixrdevelopment/RxODE");
```
And then trying the model compile again.  

Let me know;  If not, is there a way you can provide the RxODE model code, even if it is through email?

**Comment by HongtaoYu** [comment]
Hi Matt,

I am not sure you have received my reply through the email but I will write it here as well.

Thank you for your response and suggestions. 

I installed RxODE using the method that you suggested, however, it is not showing any errors but the session aborted (trying several times).

The version of the software:
Rstudio version: Version 1.2.5001 (the latest)
R version: 3.6.1 (2019-07-05)
Rtools: 3.5 (the latest)
RxODE: 0.9.1-7 (installed using: devtools::install_github("nlmixrdevelopment/RxODE");)]

I have attached the model file if you want to have a test.

“Modelfile_RBF-based” has the ODEs,
“Validation_RBF_based” has the running script (the model is compiled in this file)
Others are the parameter and initial conditions files.

Please let me know if you need anything else. Thank you!!

Regards
Hongtao

**Comment by mattfidler** [comment]
Can you send the attachments to matthew.fidler@gmail.com ?  Or you can
attach them as a zip file to this issue.

I didn't get your email.

**Comment by mattfidler** [comment]
Thank you @HongtaoYu 

I will look into this.  It may take some thought.

Matt.

**Comment by mattfidler** [comment]
Hi @HongtaoYu 

I believe I fixed your issue.  Please update from github and see if it is resolved.  That is:

```R
devtools::install_github("nlmixredevlopment/RxODE")
```

If you are OK with me using your model, I can add it to the testing suite so hopefully this doesn't happen again.

**Comment by HongtaoYu** [comment]
Matt,

Thank you so much!!

Regards
Hongtao

________________________________

**Comment by HongtaoYu** [comment]
Hi Matt,

Yes, I have installed the RxODE again, and now it works well with compiling the model. However, When I run the code, it shows other error:

Error in rxSolve_(object, .ctl, .nms, .xtra, params, events, inits, setupOnly = .setupOnly) : 
  Index out of bounds: [index='dvid'].

Yes, I am OK to add the model to the testing suite for future use. Thanks.

Regards
Hongtao

**Comment by mattfidler** [comment]
Let me look more carefully.  I just compiled the model.

**Comment by mattfidler** [comment]
Hi @HongtaoYu,

I think this fix should work. I have attached the plots from your script.

[Rplots.zip](https://github.com/nlmixrdevelopment/RxODE/files/3663987/Rplots.zip)

https://nlmixrdevelopment.github.io/RxODE.doc/articles/RxODE-speed.html

Should have information about how to run the ODE solving in parallel.

**Comment by HongtaoYu** [comment]
Dear Matt,

Thank you for your time and sharing the link with me.

Yes, the results look good. How to fix the errors, or I will need to reinstall the RxODE? Thank you.

Regards
Hongtao

**Comment by mattfidler** [comment]
To check, use:
```R
devtools::install_github("nlmixrdevelopment/RxODE")
```

**Comment by mattfidler** [comment]
Did this work for you @HongtaoYu

**Comment by HongtaoYu** [comment]
Dear Matt,

I tested that using my personal laptop, however, it didn't work. The errors are the same as before. I didn't get a chance to test that using my working laptop today, but I will let you know tomorrow. Thanks.

Regards
Hongtao

**Comment by HongtaoYu** [comment]
Dear Matt,

I have tested the RxODE, and it is working now!!!! Thanks. I very appreciate your time.

Regards
Hongtao

**Comment by mattfidler** [comment]
Thanks @HongtaoYu!  Hopefully you can get it working on your personal laptop.

If not feel free to drop me a line.
